name: PlayerTrade
authors: [alvin0319, cosmicnebula200, AGTHARN]
main: alvin0319\PlayerTrade\PlayerTrade
version: 2.1.1
api: 5.0.0

permissions:
  playertrade.command:
    description: Allows player to use /trade command
    default: true
